[project]
name = "llama-api"
version = "2025.04.30"
description = "Alaska Small Business Development Center"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "llama-api-client>=0.1.0",
]
